guide/auto-update.md
guide/faq.md
guide/inject-manifest.md
package.json
pnpm-lock.yaml

This PR includes:
- automatic reload != automatic page reload
- disabling injection point (inject manifest)
- `iief` rollup build format: unexpected service worker exports (inject manifest)

chore: add new features for `0.14` version

---

.eslintignore
.vitepress/contributors.ts
.vitepress/integrations.ts

chore: add social links for team and integration

---

README.md

Should add also SolidStart once we merge #26

docs: add meta frameworks to readme features

---

.vitepress/config.ts
guide/custom-service-worker.md
guide/service-worker-without-pwa-capabilities.md

Adding a separate Guide for faster reference on Custom Service worker support.

docs: add service worker without PWA capabilities section

---

.vitepress/config.ts
guide/static-assets.md
package.json

- update pwa plugin version to latest 0.14.6
- update minimal version for assets handling (not yet suppoted)
- includes Nuxt 3 in docs keywords meta entry
- includes Nuxt 3 and Nuxt module in package keywords

docs: update assets handling plugin version

---

frameworks/nuxt.md

Typo, 2 times offlineReady instead of updateReady and offlineReady

Update nuxt.md due to typo

---

frameworks/index.md

The list did not include nuxt 3

fix: Added nuxt 3 to the framework list

---

guide/faq.md

Removed extra word "via" from link

Removed extra word "via" in FAQ section

---

guide/pwa-minimal-requirements.md

This commit updates "masked-icon" to "mask-icon" in the document to maintain consistency with other context in the document.

Fixed typo in pwa-minimal-requirements.md

---

guide/register-service-worker.md

Just a little addition to the documentation. The information I did not find while I was reading it.

Added Information on where to find the correct Service Worker URL code.

---

assets-generator/cli.md

Really great work here guys, wanted to provide some docs updates for things not immediately clear 
- Added example of how to customize padding
- Fixed import from using relative for type

docs: added example of customizing padding in custom preset

---

assets-generator/cli.md
package.json
pnpm-lock.yaml

- bump to pnpm 8.6.12
- add favicons entry to assets generator

docs: bump to VP rc-4

---

assets-generator/cli.md

Added link and tip about resizeOptions for fit

docs(assets-generator): include resizeOptions defaults  (splash)

---

package.json

This PR updates the version and bumps to pnpm 8.7.4

docs: update version to 0.16.5

---

examples/astro.md
examples/index.md
examples/vitepress.md
frameworks/astro.md
package.json

- bump to pnpm 8.9.2
- update command to run this repo in local: `pnpm run serve` updated to `pnpm run preview` (missing serve script)
- add StackBlitz links in Astro examples
- update package version

docs: update Astro entries

---

examples/nuxt.md

docs: update Nuxt examples page

---

guide/pwa-minimal-requirements.md
package.json

docs: include new online assets generator tool

---

.eslintrc.json
.vitepress/config.ts
.vitepress/contributors.ts
.vitepress/scripts/transformHead.ts
.vitepress/theme/components/GenerateSWCleanupOutdatedCaches.md
.vitepress/theme/components/GenerateSWSourceMap.md
assets-generator/cli.md
frameworks/astro.md
frameworks/nuxt.md
frameworks/preact.md
frameworks/react.md
frameworks/solidjs.md
frameworks/svelte.md
frameworks/vitepress.md
frameworks/vue.md
guide/breaking-changes.md
guide/development.md
guide/faq.md
guide/index.md
guide/inject-manifest.md
guide/pwa-minimal-requirements.md
guide/register-service-worker.md
guide/service-worker-precache.md
package.json
pnpm-lock.yaml
tsconfig.json
workbox/inject-manifest.md

docs: bump to latest VP and PWA VP integration

---

guide/register-service-worker.md

In case this PR will be approved and merged: https://github.com/vite-pwa/vite-plugin-pwa/pull/605

docs: include information about new 'script-defer' value in `injectRegister` option

---

frameworks/nuxt.md
guide/register-service-worker.md
guide/unregister-service-worker.md
package.json
pnpm-lock.yaml

- bump to VP rc.31 (shikiji :tada: from rc.30)
- custom `selfDestroying` serice worker in unregister service worker section

docs: include Nuxt 0.3.1 and plugin 0.17.2 changes

---

.vitepress/config.ts
assets-generator/api.md
assets-generator/cli.md
assets-generator/index.md
assets-generator/migrations.md
frameworks/index.md

https://github.com/vite-pwa/assets-generator/pull/24

docs: include assets generator v0.1.0 changes

---

assets-generator/api.md

Corrects a minor typo in the documentation, and restores the associated link.

docs: update api.md

---

.vitepress/components.d.ts
.vitepress/config.ts
.vitepress/theme/components/BreakingChanges.md
.vitepress/theme/components/ChangeLog.md
frameworks/astro.md
frameworks/nuxt.md
frameworks/sveltekit.md
frameworks/vitepress.md
guide/breaking-changes.md
guide/change-log.md

https://github.com/vite-pwa/sveltekit/pull/76

docs: add SvelteKit 2 support

---

guide/change-log.md

https://github.com/vite-pwa/nuxt/pull/109

docs(nuxt): add Vite 5 and Nuxt 3.9 change log

---

assets-generator/cli.md

https://github.com/vite-pwa/assets-generator/pull/33

docs: include new PWA assets generator CLI options

---

deployment/index.md
examples/index.md

Affected Pages:
- https://vite-pwa-org.netlify.app/examples/
- https://vite-pwa-org.netlify.app/deployments/

docs: update PWA Minimal Requirements hyperlink

---

.vitepress/config.ts
README.md
assets-generator/api.md
assets-generator/integrations.md
frameworks/astro.md
frameworks/nuxt.md
frameworks/sveltekit.md
frameworks/vitepress.md
guide/change-log.md
package.json

This PR includes changes for PWA Assets Generator integration:
- https://github.com/vite-pwa/vite-plugin-pwa/pull/621

docs: include v0.19.0 changes

---

guide/change-log.md
package.json
pnpm-lock.yaml

- change log for Astro integration 0.3.1
- bump to VitePress 1.0.0 💯 ❤️ 
- bump to pnpm 8.15.5

docs: include changes in 0.19.6

---

frameworks/nuxt.md
package.json

https://github.com/vite-pwa/nuxt/pull/125

docs: use new `nuxi module add` command in installation

---

deployment/netlify.md
deployment/vercel.md

This pull request includes necessary updates to deploy our Vite PWA on Vercel efficiently. It introduces a `vercel.json` configuration file that specifies HTTP headers for optimal caching and security, mirroring some settings typically used with Netlify but adapted for Vercel.
1. **`vercel.json` Configuration**:
- Added new caching rules for HTML pages, service workers, and assets to enhance load times and user experience.
- Set up security headers to protect against common vulnerabilities and ensure content integrity.
- Included rewrites to ensure all requests are routed correctly within our SPA.
2. **Deployment Instructions**:
- Detailed steps on preparing the application, setting up the project on Vercel, and verifying deployment to ensure everything functions as expected.
3. …

docs: add Vercel deployment instructions

---

.vitepress/theme/components/ScaffoldingPWAProject.md

Clarify supported Node.js versions in `<ScaffoldingPWAProject />`.

Clarify "scaffolding PWA project" reusable component

---

guide/periodic-sw-updates.md

docs: update periodic-sw-updates.md example code

---

guide/static-assets.md
package.json

https://github.com/vite-pwa/vite-plugin-pwa/pull/733

docs: update static assets with tinyglobby instead fast-glob

---

package.json
pnpm-lock.yaml

This Pr also updates dependencies.

docs: bump pnpm to 9.10.0

---

guide/change-log.md
package.json
pnpm-lock.yaml

This PR also updates `pnpm` to `9.14.4`

docs: include Workbox 7.3.0 and Vite 6 changes
