frameworks/sveltekit.md
`hydrate` no longer exists and SvelteKit's service worker now works in dev mode. SvelteKit's dev-mode support only works in Chrome though - I'm not sure if there's any restriction like that in the PWA plugin? If not, we could add back that sentence with the additional clarification
=> Update SvelteKit docs to reflect latest version

vite.config.ts
Updating to Vite 4 and refreshing any page breaks page or partial page content with `Hydration completed but contains mismatches` error.
=> fix: hydration error

deployment/nginx.md
Without the `include mime.types;` directive within the `server` block `types` overrides system ones and in effect all files except `.webmanifest` are served with `Content-Type: application/octet-stream`.
See this [SO answer](https://stackoverflow.com/a/37330325/1012616) for more details
=> NGINX: Load default system mime types

guide/inject-manifest.md
Just a small docs update to hopefully save someone a lot of pain.
Whilst following the docs for injecting a custom service worker I kept running into the `Cannot use import statement outside a module` error. After spending a long time on it, I eventually found that it's 100% answered in the docs already, so I'm just making that more clear.
I think this could be a pretty common use case, a user is developing a custom service worker, they're reading the custom service worker docs and they're copying the code samples with imports in them, so hopefully this is useful.
Cheers
=> docs: Updates inject-manifest docs to explicitly mention devOptions

deployment/index.md
`Vercel` is linked to AWS Amplify
=> Fix wrong link

deployment/netlify.md
Netlify now supports pnpm out of box. See: https://www.netlify.com/blog/how-to-use-pnpm-with-netlify-build/
=> Remove pnpm workaround from netlify.toml

frameworks/sveltekit.md
The old link now just goes to the introduction, presumably because SvelteKit docs is now split into many pages.
=> Fix link to SvelteKit service worker module

frameworks/sveltekit.md, package.json
Add the new kit option `latestKit` and the corresponding warning: https://github.com/vite-pwa/sveltekit/pull/32.
/cc @benmccann should we release a minor (breaking changes: check the warning on the page)?
=> docs: include new SvelteKit options

.vitepress/config.ts, frameworks/sveltekit.md
This PR also updates SvelteKit entry about disabling kit sw registration, `plugins` entry is wrong, it should be `kit`.
=> fix: wrong edit page link

frameworks/sveltekit.md
According to vite-pwa/sveltekit/issues/55 we wanted to add some more clarity to the svelteKit setup process. This addresses the problems mentioned in the referenced issue. 
This is a starting point. I will try to create an [adder](https://github.com/svelte-add/svelte-add) for this, so that this can be setup with less trouble in the future.
FYI @userquin
=> Add webmanifest link generation to sveltekit tutorial

.vitepress/theme/components/ReactReactiveWarning.md, frameworks/preact.md, frameworks/react.md
For React and Preact:
- Addressing https://github.com/vite-pwa/vite-plugin-pwa/issues/536
- Warn about the options is not reactive
The text added:
> The options provided to hooks are not reactive. Therefore, the callback references will be the first rendered options instead of the latest hook’s options. If you are doing complex logic with state changes, you will need to provide a stable reference function.
---
Although other frameworks examples may also suffer from same behavior, React and Preact are more likely to be misused due to how reactive works in both of them.
=> docs: update react and preact hook warn

frameworks/sveltekit.md
Just a stylistic adjustment - this is a cleaner method of lazy-loading in Svelte components client-side. Don't know if you care. :)
Pairs with https://github.com/vite-pwa/sveltekit/pull/57
=> docs: Easier component lazy-load method

guide/index.md
What title says :P 
PD: Is the [`docs` dir in `vite-plugin-pwa`](https://github.com/vite-pwa/vite-plugin-pwa/tree/31ccaa89bb18b7d39f8d150435b26d33dfee04dd/docs) used? Seems like a replica of this repo. I can make a PR in there to remove that if it's helpful :) 
thx
=> docs: fix broken link to Elk PWA page

.vitepress/theme/PwaLayout.vue, .vitepress/theme/components/ReloadPrompt.vue, .vitepress/theme/index.ts, .vitepress/theme/styles/main.css, .vitepress/theme/styles/vars.css, index.md, package.json, pnpm-lock.yaml, tsconfig.json
This PR also changes the VP layout to add radial transition on theme switch: 
- changed main and vars styles with new VP variables
- tip, info, warning and info styles with current borders and colors: VP has changed them.
This PR also includes a few changes to the prompt for update PWA dialog (adds a small border, will be there after 2 updates) and also changing colors in Excalidraw SVG images on theme switch to meet WCAG AA:
=> docs: bump VP to rc10

guide/breaking-changes.md, package.json, pnpm-lock.yaml
This PR includes:
- update dependencies
- add Astro and Nuxt breaking changes: Vite 5 and Rollup 4 and `dontCacheBustURLsMatching`
=> docs: include latest 0.17 changes

assets-generator/cli.md
In one of the examples, `Preset` and `2023` is swapped around.
=> docs: correct import of preset

assets-generator/cli.md
https://github.com/vite-pwa/assets-generator/pull/31
=> docs(assets): add custom image source for dark splash screens feature

assets-generator/integrations.md, frameworks/astro.md, frameworks/sveltekit.md, frameworks/vitepress.md, guide/change-log.md, index.md, package.json, pnpm-lock.yaml
- updates pwa plugin and pwa vp versions to 0.19.0 and 0.4.0 respectivelly
- includes PWA Assets Integration in the home features
- VP 1.0.0.rc-44 reduces the build size 500KB (using svg in css)
- links for pwa assets integrations (meta-frameworks)
=> docs: update VP to 1.0.0.rc-44

guide/service-worker-without-pwa-capabilities.md
`injectManifest.injectionPoint` was set to `null` in the example but according to the types, it can be `string | undefined`, so updated the value in the example to be `undefined`.
=> docs: update service-worker-without-pwa-capabilities.md

.vitepress/config.ts
I think the navbar icon should point to main repo instead of the docs repo. People wanting to contribute to the docs can use the "Suggest changes to this page" link.
=> docs: point to main repo from navbar

.vitepress/config.ts, deployment/index.md, frameworks/remix.md, guide/change-log.md, guide/cookbook.md, guide/faq.md, guide/index.md, guide/inject-manifest.md, guide/periodic-sw-updates.md, guide/service-worker-precache.md, guide/static-assets.md, package.json, pnpm-lock.yaml, workbox/generate-sw.md, workbox/index.md, workbox/inject-manifest.md
- update pwa and vitepress
- update all chrome links: web.dev and workbox links
- include [Remix PWA](https://remix-pwa.run) link in fw entry
- update pnpm to 9.0.6
=> docs: include 0.20.0 changes

.vitepress/config.ts, guide/change-log.md, guide/scaffolding.md
- removes the `New` Bagde from the aside and from the page title
- inludes `create-pwa` link and changes in change log page
=> docs: include create-pwa v0.6.0 changes
